build:
  stage: build
  script:
  - echo "Build always"
  tags:
  - shell

test:
  stage: test
  script:
  - echo "This is testing in $CI_JOB_STAGE"
  except:
    refs:
    - master
  only:
    variables:
    - $DOCKER == null
  tags:
  - shell
 
deploy:
  stage: deploy
  script:
  - echo "This is a deployment"
  artifacts:
    - README.md
  tags:
  - shell

build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    refs:
    - master
    variables:
    - $DOCKER != null
  tags:
    - docker

build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    refs:
    - master
  only:
    variables:
     - $DOCKER != null
  tags:
    - docker
